name: mozak
description: Data collection app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  http: ^0.13.4



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_typeahead: ^4.6.0
  cupertino_icons: ^1.0.5
  intl: any
  gsheets: ^0.4.2
  connectivity_plus: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_easyloading: ^3.0.5
  email_auth: ^1.0.0
  email_otp: ^2.0.1
  autocomplete_textfield: ^2.0.1
  email_validator: ^2.1.17




dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/form_ui_assets/
    - assets/images/form_ui_assets/lottie/
  fonts:
    - family: FocusGrotesk
      fonts:
        - asset: fonts/focusgroteskbold.otf
        - asset: fonts/focusgroteskregular.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
